FROM debezium/connect:2.6

ENV BOOTSTRAP_SERVERS=localhost:9092
ENV GROUP_ID=cdc-connect
ENV CONFIG_STORAGE_TOPIC=cdc_connect_configs
ENV OFFSET_STORAGE_TOPIC=cdc_connect_offsets
ENV STATUS_STORAGE_TOPIC=cdc_connect_status
